### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by cauliflower69** [CrazyPants/EnderIO#1773]
http://pastebin.com/CMXehEMi

**Comment by MatthiasMann** [comment]
This has already been fixed in EnderIO build 320

**Comment by cauliflower69** [comment]
Sorry about that and thanks for the quick reply.

**Comment by Xules01** [comment]
I've been trying to upgrade to current versions of EnderIO and Applied Energistics for some time.  
Recently moved from 1.7.2 to 1.7.10.   Having to run EnderIO-1.7.10-2.2.1.276.  

Made a bit of progress today after removing all my capacitor banks.  The world still crashes though when I try connecting a capacitor bank to something that ticks energy I think.  
running EnderIO-1.7.10-2.2.7.325 & appliedenergistics2-rv2-beta-8.  Also had a different error from EnhancedPortals_1.7.10-universal-3.0.10 when it was connected to an energy conduit.

This happens on new worlds as well

Time: 1/25/15 6:42 PM
Description: Ticking block entity

java.lang.IncompatibleClassChangeError: vtable stub
	at crazypants.enderio.power.EnergyReceiverPI.recieveEnergy(EnergyReceiverPI.java:66)
	at crazypants.enderio.power.PowerDistributor.transmitEnergy(PowerDistributor.java:46)
	at crazypants.enderio.machine.generator.combustion.TileCombustionGenerator.transmitEnergy(TileCombustionGenerator.java:200)
	at crazypants.enderio.machine.generator.combustion.TileCombustionGenerator.processTasks(TileCombustionGenerator.java:177)
	at crazypants.enderio.machine.AbstractMachineEntity.func_145845_h(AbstractMachineEntity.java:276)
	at crazypants.enderio.machine.AbstractPoweredMachineEntity.func_145845_h(AbstractPoweredMachineEntity.java:31)

**Comment by tterrag1098** [comment]
Some mod of yours has an old RF API.
